### ISSUE TITLE
QuickCopy produce error message when Field "Author" is emtpy

### ISSUE THREAD

**Issue by Finessest** [silentdot/zotero-markdown-translator#2]
Hi @silentdot,

First of all thanks a lot for the script you built. This adds a big value to the Obsidian and Zotero community.

After using a while, I realized that the field "Author" is mandatory for the QuickCopy ([see the error message](https://user-images.githubusercontent.com/73827361/100593193-6607d680-32f8-11eb-82b9-200fbd045d6c.png)). This can be problematic depending on the item you choose to import into Zotero. For example, the item-type "Web-Page" doesn't have always have an author.

Could you make in a near-future release similar behave like the field "Date", if the field is empty, it'll be completely ignored in the markdown URL format?

**Comment by silentdot** [comment]
Hey, 

thanks for the kind words. 
That should be an easy fix, let me look into it. I will message you if I have a new release ready.

**Comment by silentdot** [comment]
Hey, 

I have published a new version, the problem should be fixed.

Let me know if it works for you :)

**Comment by Finessest** [comment]
Hello,

That was fast. I have tested it and it works without any problems. Thank you very much.
